[package]
name = "hubuum-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rustyline = "14"
cli_command_derive = { path = "./cli_command_derive" }
thiserror = "1"
env_logger = "0"
log = "0"
shlex = "1"
reqwest = { version = "0", features = ["blocking"] }
chrono = { version = "0", features = ["serde"] }
once_cell = "1"
regex = "1"
lazy_static = "1"
colored = "2"
anyhow = "1"
dirs = "5"
config = "0"
clap = { version = "4", features = ["derive"] }
hubuum_client = { path = "../hubuum-client-rust" }
rpassword = "7"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
