[package]
name = "rustyline-with-structs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rustyline = "14"
cli_command_derive = { path = "./cli_command_derive" }
thiserror = "1"
env_logger = "0"
log = "0"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
